@echo off
echo Starting app1.bat...
start C:\Users\91798\Documents\BeBest\Logins\s1.bat
echo Starting app1.bat...
start C:\Users\91798\Documents\BeBest\support\s2.bat
echo Starting app3.bat...
start C:\Users\91798\Documents\BeBest\Dashboard\s3.bat
echo Starting app3.bat...
start C:\Users\91798\Documents\BeBest\Dashboard\s5.bat
echo Starting app4.bat...
start C:\Users\91798\Documents\BeBest\other\s4.bat
echo All scripts are running in separate windows.
pause
